import { classifyFingerprint, fingerprintTokens } from "./fingerprint";
import type { ConvergenceOptions, InvalidReview, LedgerCounts, ObjectionLedger, ObjectionLedgerEntry, ReviewSeverity, StructuredClaudeReview } from "./types";
const rank:Record<ReviewSeverity,number>={LOW:1,MEDIUM:2,HIGH:3}; export const severityRank=(x:ReviewSeverity)=>rank[x];
export class InvalidLedgerIngestError extends Error{constructor(public readonly invalidReview:InvalidReview){super(invalidReview.reason);}}
export const createEmptyLedger=():ObjectionLedger=>({entries:[],nextId:1}); export const cloneLedger=(l:ObjectionLedger):ObjectionLedger=>({nextId:l.nextId,entries:l.entries.map(e=>({...e,normalizedFingerprint:[...e.normalizedFingerprint],history:e.history.map(h=>({...h}))}))});
export function countsForLedger(l:ObjectionLedger):LedgerCounts{return{openHighCount:l.entries.filter(e=>e.status==="OPEN"&&e.severity==="HIGH").length,openMediumCount:l.entries.filter(e=>e.status==="OPEN"&&e.severity==="MEDIUM").length,openLowCount:l.entries.filter(e=>e.status==="OPEN"&&e.severity==="LOW").length}}
function add(e:ObjectionLedgerEntry,r:number,kind:ObjectionLedgerEntry["history"][number]["kind"],detail?:string){e.history.push({round:r,kind,...(detail===undefined?{}:{detail})});} function adjust(e:ObjectionLedgerEntry,s:ReviewSeverity,r:number){if(rank[s]>rank[e.severity]){const old=e.severity;e.severity=s;if(rank[s]>rank[e.highestSeveritySeen])e.highestSeveritySeen=s;add(e,r,"SEVERITY_CHANGED",old+" -> "+s);}else if(rank[s]<rank[e.severity])add(e,r,"SEVERITY_DOWNGRADE_REJECTED",e.severity+" -> "+s);}
function reopen(e:ObjectionLedgerEntry,s:ReviewSeverity|undefined,r:number,note:string){const old=e.severity,w=s??e.severity,effective=rank[w]>=rank[e.highestSeveritySeen]?w:e.highestSeveritySeen;e.status="OPEN";e.severity=effective;if(rank[effective]>rank[e.highestSeveritySeen])e.highestSeveritySeen=effective;if(old!==effective)add(e,r,"SEVERITY_CHANGED",old+" -> "+effective+" (reopen floor)");add(e,r,"REOPENED",note);e.lastSeenRound=r;}
export interface LedgerIngestResult{ledger:ObjectionLedger;touchedEntryIds:string[];newEntryIds:string[];reopenedEntryIds:string[];clean:boolean}
export function ingestReview(input:ObjectionLedger,review:StructuredClaudeReview|InvalidReview,round:number,options:ConvergenceOptions):LedgerIngestResult{if("invalid"in review)throw new InvalidLedgerIngestError(review);const l=cloneLedger(input),touched=new Set<string>(),explicitTouched=new Set<string>(),reopened=new Set<string>();for(const id of review.resolvedObjectionIds){const e=l.entries.find(x=>x.id===id);if(!e||e.status!=="OPEN")throw new InvalidLedgerIngestError({invalid:true,rawText:review.rawText,reason:"unknown or non-open objection id in resolvedObjectionIds: "+id});e.status="RESOLVED";e.lastSeenRound=round;add(e,round,"RESOLVED",review.resolutionEvidence[id]);touched.add(id);explicitTouched.add(id);}for(const x of review.stillOpenObjections){const e=l.entries.find(y=>y.id===x.id);if(!e||e.status!=="OPEN")throw new InvalidLedgerIngestError({invalid:true,rawText:review.rawText,reason:"unknown or non-open objection id in stillOpenObjections: "+x.id});e.lastSeenRound=round;add(e,round,"REPEATED");if(x.severityOverride)adjust(e,x.severityOverride,round);touched.add(x.id);explicitTouched.add(x.id);}for(const x of review.reopenedObjections){const e=l.entries.find(y=>y.id===x.id);if(!e||!(e.status==="RESOLVED"||e.status==="REJECTED"))throw new InvalidLedgerIngestError({invalid:true,rawText:review.rawText,reason:"unknown or non-reopenable objection id in reopenedObjections: "+x.id});reopen(e,x.severityOverride,round,x.note);touched.add(x.id);explicitTouched.add(x.id);reopened.add(x.id);}
const fresh:string[]=[];for(const x of review.newObjections){const tokens=fingerprintTokens(x);const duplicate=l.entries.find(e=>e.firstSeenRound===round&&e.status==="OPEN"&&e.normalizedFingerprint.length===tokens.length&&e.normalizedFingerprint.every((token,index)=>token===tokens[index]));if(duplicate){if(explicitTouched.has(duplicate.id))throw new InvalidLedgerIngestError({invalid:true,rawText:review.rawText,reason:"newObjections entry fingerprint-matches "+duplicate.id+", which is already referenced elsewhere in this review"});add(duplicate,round,"DUPLICATE_COLLAPSED",x.summary+" | "+x.reason);adjust(duplicate,x.severity,round);touched.add(duplicate.id);continue;}const m=classifyFingerprint(x,l.entries,options);if(m.kind==="MERGE"&&m.entry){const e=m.entry;if(explicitTouched.has(e.id))throw new InvalidLedgerIngestError({invalid:true,rawText:review.rawText,reason:"newObjections entry fingerprint-matches "+e.id+", which is already referenced elsewhere in this review"});const old=e.status;const prior=e.summary+" | "+e.reason;e.summary=x.summary;e.reason=x.reason;e.normalizedFingerprint=tokens;e.lastSeenRound=round;if(old==="OPEN"){add(e,round,"PARAPHRASED",prior);adjust(e,x.severity,round);}else{reopen(e,x.severity,round,"fingerprint-derived reopen");reopened.add(e.id);}touched.add(e.id);}else{const e:ObjectionLedgerEntry={id:"OBJ-"+l.nextId++,severity:x.severity,highestSeveritySeen:x.severity,summary:x.summary,reason:x.reason,status:"OPEN",firstSeenRound:round,lastSeenRound:round,normalizedFingerprint:tokens,history:[]};add(e,round,"RAISED",m.possibleDuplicate?"possible duplicate of "+m.possibleDuplicate.id:undefined);l.entries.push(e);fresh.push(e.id);touched.add(e.id);}}
for(const e of l.entries)if(e.status==="OPEN"&&!touched.has(e.id)){e.lastSeenRound=round;add(e,round,"IMPLICITLY_CARRIED_OPEN");}const c=countsForLedger(l);return{ledger:l,touchedEntryIds:[...touched],newEntryIds:fresh,reopenedEntryIds:[...reopened],clean:c.openHighCount===0&&c.openMediumCount===0};}
export const ingestStructuredReview=ingestReview;
